config/routes.rb
Rails.application.routes.draw do
  get 'teams/login', :defaults => { format: :json }
  post 'teams/login', :defaults => { format: :json }
  post 'teams/logout', :defaults => { format: :json }

  get 'home/status', :defaults => { format: :json }
  get 'home/index'

  get 'areas/riddle', :defaults => { format: :json }
  post 'areas/solve_riddle/id', :defaults => { format: :json }

  post 'flags/solve', :defaults => { format: :json }

  get 'achievements/all', :defaults => { format: :json }

  get 'puzzle_piece_reveals/get', :defaults => { format: :json }

  root 'home#index'

  resources :achievement_successes
  resources :controls
  resources :achievements
  resources :flags
  resources :areas
  resources :teams
  resources :puzzle_pieces
  resources :puzzle_piece_reveals

end

app/models/control.rb
class Control < ActiveRecord::Base

  belongs_to :area
  belongs_to :team

end

app/controllers/controls_controller.rb
class ControlsController < ApplicationController

  before_action :authenticate_admin
  before_action :set_control, only: [:show, :edit, :update, :destroy]

  # GET /controls
  # GET /controls.json
  def index
    @controls = Control.all
  end

  # GET /controls/1
  # GET /controls/1.json
  def show
  end

  # GET /controls/new
  def new
    @control = Control.new
  end

  # GET /controls/1/edit
  def edit
  end

  # POST /controls
  # POST /controls.json
  def create
    @control = Control.new(control_params)

    respond_to do |format|
      if @control.save
        format.html { redirect_to @control, notice: 'Control was successfully created.' }
        format.json { render :show, status: :created, location: @control }
      else
        format.html { render :new }
        format.json { render json: @control.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /controls/1
  # PATCH/PUT /controls/1.json
  def update
    respond_to do |format|
      if @control.update(control_params)
        format.html { redirect_to @control, notice: 'Control was successfully updated.' }
        format.json { render :show, status: :ok, location: @control }
      else
        format.html { render :edit }
        format.json { render json: @control.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /controls/1
  # DELETE /controls/1.json
  def destroy
    @control.destroy
    respond_to do |format|
      format.html { redirect_to controls_url, notice: 'Control was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_control
      @control = Control.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def control_params
      params.require(:control).permit(:area_id, :team_id, :isOver)
    end
end

app/helpers/controls_helper.rb
module ControlsHelper
end

app/views/controls/_form.html.erb
<%= form_for(@control) do |f| %>
  <% if @control.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@control.errors.count, "error") %> prohibited this control from being saved:</h2>

      <ul>
      <% @control.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :area_id %><br>
    <%= f.text_field :area_id %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br>
    <%= f.text_field :team_id %>
  </div>
  <div class="field">
    <%= f.label :isOver %><br>
    <%= f.check_box :isOver %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/controls/edit.html.erb
<h1>Editing Control</h1>

<%= render 'form' %>

<%= link_to 'Show', @control %> |
<%= link_to 'Back', controls_path %>

app/views/controls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Controls</h1>

<table>
  <thead>
    <tr>
      <th>Area</th>
      <th>Team</th>
      <th>Isover</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @controls.each do |control| %>
      <tr>
        <td><%= control.area %></td>
        <td><%= control.team %></td>
        <td><%= control.isOver %></td>
        <td><%= link_to 'Show', control %></td>
        <td><%= link_to 'Edit', edit_control_path(control) %></td>
        <td><%= link_to 'Destroy', control, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Control', new_control_path %>

app/views/controls/new.html.erb
<h1>New Control</h1>

<%= render 'form' %>

<%= link_to 'Back', controls_path %>

app/views/controls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Area:</strong>
  <%= @control.area %>
</p>

<p>
  <strong>Team:</strong>
  <%= @control.team %>
</p>

<p>
  <strong>Isover:</strong>
  <%= @control.isOver %>
</p>

<%= link_to 'Edit', edit_control_path(@control) %> |
<%= link_to 'Back', controls_path %>