config/routes.rb
Rails.application.routes.draw do
  get 'teams/login', :defaults => { format: :json }
  post 'teams/login', :defaults => { format: :json }
  post 'teams/logout', :defaults => { format: :json }

  get 'home/status', :defaults => { format: :json }
  get 'home/index'

  get 'areas/riddle', :defaults => { format: :json }
  post 'areas/solve_riddle/id', :defaults => { format: :json }

  post 'flags/solve', :defaults => { format: :json }

  get 'achievements/all', :defaults => { format: :json }

  get 'puzzle_piece_reveals/get', :defaults => { format: :json }

  root 'home#index'

  resources :achievement_successes
  resources :controls
  resources :achievements
  resources :flags
  resources :areas
  resources :teams
  resources :puzzle_pieces
  resources :puzzle_piece_reveals

end

app/models/area.rb
class Area < ActiveRecord::Base

  belongs_to :team
  has_many :controls
  has_many :teams, :through => :controls
  has_many :flags

  def current_team_control
    current_teams = controls.find_by_isOver(false)
    if current_teams
      current_teams
    else
      nil
    end
  end

  def current_team
    current_teams = controls.find_by_isOver(false)
    if current_teams
      current_teams.team
    else
      nil
    end
  end

  def status_hash(team)
    {
        area_id: id,
        controlling_team: current_team,
        points: points,
        flags_count: flags.count,
        was_controlled: teams.include?(team)
    }
  end

  def transfer_control
    new_team = team_in_session
    old_team_control = current_team_control
    if old_team_control
      old_team_control.isOver = true
      old_team_control.save
    end
    Control.create team: new_team, area: self, isOver: false
  end

end

app/controllers/areas_controller.rb
class AreasController < ApplicationController

  before_action :authenticate_admin, :except => [:riddle, :solve_riddle]
  before_action :authenticate_user, :only => [:riddle, :solve_riddle]
  before_action :set_area, only: [:show, :edit, :update, :destroy, :riddle, :solve_riddle]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def riddle
    respond_to do |format|
      format.json {render json: { riddle: @area.riddle_text.html_safe } }
    end
  end

  def solve_riddle
    if @area.riddle_answer == params[:answer]
      @area.transfer_control
      respond_to do |format|
        format.json {render json: { result: true, points: @area.points } }
      end
    else
      respond_to do |format|
        format.json {render json: { result: false } }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:x_coord, :y_coord, :riddle_text, :riddle_answer, :points)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_for(@area) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :x_coord %><br>
    <%= f.number_field :x_coord %>
  </div>
  <div class="field">
    <%= f.label :y_coord %><br>
    <%= f.number_field :y_coord %>
  </div>
  <div class="field">
    <%= f.label :riddle_text %><br>
    <%= f.text_area :riddle_text %>
  </div>
  <div class="field">
    <%= f.label :riddle_answer %><br>
    <%= f.text_field :riddle_answer %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form' %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Areas</h1>

<table>
  <thead>
    <tr>
      <th>X coord</th>
      <th>Y coord</th>
      <th>Riddle text</th>
      <th>Riddle answer</th>
      <th>Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.x_coord %></td>
        <td><%= area.y_coord %></td>
        <td><%= area.riddle_text %></td>
        <td><%= area.riddle_answer %></td>
        <td><%= area.points %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form' %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>X coord:</strong>
  <%= @area.x_coord %>
</p>

<p>
  <strong>Y coord:</strong>
  <%= @area.y_coord %>
</p>

<p>
  <strong>Riddle text:</strong>
  <%= @area.riddle_text %>
</p>

<p>
  <strong>Riddle answer:</strong>
  <%= @area.riddle_answer %>
</p>

<p>
  <strong>Points:</strong>
  <%= @area.points %>
</p>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>