config/routes.rb
Rails.application.routes.draw do
  get 'teams/login', :defaults => { format: :json }
  post 'teams/login', :defaults => { format: :json }
  post 'teams/logout', :defaults => { format: :json }

  get 'home/status', :defaults => { format: :json }
  get 'home/index'

  get 'areas/riddle', :defaults => { format: :json }
  post 'areas/solve_riddle/id', :defaults => { format: :json }

  post 'flags/solve', :defaults => { format: :json }

  get 'achievements/all', :defaults => { format: :json }

  get 'puzzle_piece_reveals/get', :defaults => { format: :json }

  root 'home#index'

  resources :achievement_successes
  resources :controls
  resources :achievements
  resources :flags
  resources :areas
  resources :teams
  resources :puzzle_pieces
  resources :puzzle_piece_reveals

end

app/models/puzzle_piece.rb
class PuzzlePiece < ActiveRecord::Base

  has_many :puzzle_piece_reveals
  has_many :teams, :through => :puzzle_piece_reveals

end

app/controllers/puzzle_pieces_controller.rb
class PuzzlePiecesController < ApplicationController

  before_action :authenticate_admin, :except => [:get]
  before_action :authenticate_user, :only => [:get]
  before_action :set_puzzle_piece, only: [:show, :edit, :update, :destroy]

  # GET /puzzle_pieces
  # GET /puzzle_pieces.json
  def index
    @puzzle_pieces = PuzzlePiece.all
  end

  # GET /puzzle_pieces/1
  # GET /puzzle_pieces/1.json
  def show
  end

  # GET /puzzle_pieces/new
  def new
    @puzzle_piece = PuzzlePiece.new
  end

  # GET /puzzle_pieces/1/edit
  def edit
  end

  # POST /puzzle_pieces
  # POST /puzzle_pieces.json
  def create

    uploaded_file = params[:person][:picture]
    File.open(Rails.root.join('public', 'uploads', 'puzzle', uploaded_file.original_filename), 'wb') do |file|
      file.write uploaded_file.read
    end

    @puzzle_piece = PuzzlePiece.new(puzzle_piece_params)

    respond_to do |format|
      if @puzzle_piece.save
        format.html { redirect_to @puzzle_piece, notice: 'Puzzle piece was successfully created.' }
        format.json { render :show, status: :created, location: @puzzle_piece }
      else
        format.html { render :new }
        format.json { render json: @puzzle_piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puzzle_pieces/1
  # PATCH/PUT /puzzle_pieces/1.json
  def update
    respond_to do |format|
      if @puzzle_piece.update(puzzle_piece_params)
        format.html { redirect_to @puzzle_piece, notice: 'Puzzle piece was successfully updated.' }
        format.json { render :show, status: :ok, location: @puzzle_piece }
      else
        format.html { render :edit }
        format.json { render json: @puzzle_piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puzzle_pieces/1
  # DELETE /puzzle_pieces/1.json
  def destroy
    @puzzle_piece.destroy
    respond_to do |format|
      format.html { redirect_to puzzle_pieces_url, notice: 'Puzzle piece was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get
    team = team_in_session
    if team.deserve_another_piece? && params[:piece_x] && params[:piece_y]
      puzzle_piece = PuzzlePiece.find(x_coord: params[:piece_x], y_coord: params[:piece_y])
      PuzzlePieceReveal.create :puzzle_piece => puzzle_piece, :team => team
      respond_to do |format|
        format.json { render json: { piece: puzzle_piece } }
      end
    else
      respond_to do |format|
        format.json { render json: { piece: nil } }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puzzle_piece
      @puzzle_piece = PuzzlePiece.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puzzle_piece_params
      params.require(:puzzle_piece).permit(:x_coord, :y_coord, :image_uri, :note)
    end
end

app/helpers/puzzle_pieces_helper.rb
module PuzzlePiecesHelper
end

app/views/puzzle_pieces/_form.html.erb
<%= form_for(@puzzle_piece, :html => { :multipart => true }) do |f| %>
  <% if @puzzle_piece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@puzzle_piece.errors.count, "error") %> prohibited this puzzle_piece from being saved:</h2>

      <ul>
      <% @puzzle_piece.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :x_coord %><br>
    <%= f.number_field :x_coord %>
  </div>
  <div class="field">
    <%= f.label :y_coord %><br>
    <%= f.number_field :y_coord %>
  </div>
  <div class="field">
    <%= f.label :image_uri %><br>
    <%= f.file :image_uri %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_field :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/puzzle_pieces/edit.html.erb
<h1>Editing Puzzle Piece</h1>

<%= render 'form' %>

<%= link_to 'Show', @puzzle_piece %> |
<%= link_to 'Back', puzzle_pieces_path %>

app/views/puzzle_pieces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Puzzle Pieces</h1>

<table>
  <thead>
    <tr>
      <th>X coord</th>
      <th>Y coord</th>
      <th>Image uri</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @puzzle_pieces.each do |puzzle_piece| %>
      <tr>
        <td><%= puzzle_piece.x_coord %></td>
        <td><%= puzzle_piece.y_coord %></td>
        <td><%= puzzle_piece.image_uri %></td>
        <td><%= puzzle_piece.note %></td>
        <td><%= link_to 'Show', puzzle_piece %></td>
        <td><%= link_to 'Edit', edit_puzzle_piece_path(puzzle_piece) %></td>
        <td><%= link_to 'Destroy', puzzle_piece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Puzzle piece', new_puzzle_piece_path %>

app/views/puzzle_pieces/new.html.erb
<h1>New Puzzle Piece</h1>

<%= render 'form' %>

<%= link_to 'Back', puzzle_pieces_path %>

app/views/puzzle_pieces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>X coord:</strong>
  <%= @puzzle_piece.x_coord %>
</p>

<p>
  <strong>Y coord:</strong>
  <%= @puzzle_piece.y_coord %>
</p>

<p>
  <strong>Image uri:</strong>
  <%= @puzzle_piece.image_uri %>
</p>

<p>
  <strong>Note:</strong>
  <%= @puzzle_piece.note %>
</p>

<%= link_to 'Edit', edit_puzzle_piece_path(@puzzle_piece) %> |
<%= link_to 'Back', puzzle_pieces_path %>